import XCTest
import UIKit

/// Photographs the iPhone's home screen so the Bundles widget can be verified without a human
/// looking at the phone.
///
/// Why this exists: `devicectl` has no screenshot command, and libimobiledevice's
/// `idevicescreenshot` needs the legacy developer disk image, which Xcode stops shipping after
/// iOS 16.4 — on iOS 17+ the `screenshotr` service is simply refused. XCUITest is the one path
/// that still works, because the test runs *on* the device and `XCUIScreen.main.screenshot()`
/// captures whatever is on screen, Springboard included.
///
/// This target deliberately lives outside `ios/` — that directory is regenerated by
/// `npx expo prebuild`, which would delete anything added to the app project.
final class WidgetShotUITests: XCTestCase {

  override func setUpWithError() throws {
    continueAfterFailure = false
  }

  /// Go to the home screen and attach a full-screen capture to the test results.
  func testCaptureHomeScreen() throws {
    captureAllHomePages(prefix: "home")
  }

  /// Open Bundles (which triggers `useWidgetSync` -> `advanceStack` -> `updateSnapshot`), return to the
  /// home screen, and capture. This is the "does one app open change the widget" test — run it
  /// repeatedly to watch the smart stack advance.
  func testOpenBundlesThenCaptureHomeScreen() throws {
    let bundles = XCUIApplication(bundleIdentifier: "com.nikhilsinha.bundles")
    bundles.launch()

    // The sync does a network fetch, a signed-URL round trip, and an image download before it calls
    // updateSnapshot. Cutting this short kills the sync mid-flight.
    Thread.sleep(forTimeInterval: 10)
    attach(XCUIScreen.main.screenshot(), named: "in-app")

    captureAllHomePages(prefix: "after-open")
  }

  /// Open the URL in `WIDGET_SHOT_URL` the way a widget tap does, and photograph where it lands.
  ///
  /// This is how the `widgetURL` deep link gets verified without a human thumb. Tapping the widget
  /// itself isn't scriptable — a widget's accessibility tree is opaque — but the tap's *effect* is
  /// just "the system opens this URL against the app", which `XCUISystem.open` reproduces exactly.
  /// What it proves is the half that was actually broken: that the app routes `bundles://…` to the
  /// right screen. That the widget carries the URL at all is visible in the App Group plist.
  func testOpenDeepLink() throws {
    let raw = ProcessInfo.processInfo.environment["WIDGET_SHOT_URL"] ?? "bundles://music"
    guard let url = URL(string: raw) else {
      XCTFail("WIDGET_SHOT_URL is not a valid URL: \(raw)")
      return
    }

    // Start from a cold-ish state so we can't mistake "the app was already on that screen" for
    // "the deep link worked".
    let bundles = XCUIApplication(bundleIdentifier: "com.nikhilsinha.bundles")
    bundles.terminate()
    Thread.sleep(forTimeInterval: 2)

    XCUIDevice.shared.system.open(url)

    // The destination screens fetch a signed URL and an image before they render anything.
    Thread.sleep(forTimeInterval: 12)
    attach(XCUIScreen.main.screenshot(), named: "deeplink")
  }

  /// Photograph Notification Center, to prove a push actually arrived.
  ///
  /// A banner is gone in about five seconds — far shorter than the time it takes to start a UI
  /// test — so racing it is hopeless. Notification Center keeps the delivered notification around,
  /// which makes it the only reliable surface to screenshot after the fact.
  func testCaptureNotificationCenter() throws {
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 2)

    // Swipe down from the very top-left; from the middle iOS opens Control Center instead.
    let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
    let top = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.0))
    let down = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.7))
    top.press(forDuration: 0.1, thenDragTo: down)
    Thread.sleep(forTimeInterval: 3)

    attach(XCUIScreen.main.screenshot(), named: "notification-center")
  }

  /// Settle, with pictures, whether a Live Activity is visible and updatable — and in which app
  /// states.
  ///
  /// PLAN.md rejected the M7 Live Activity branch on an Apple HIG sentence ("appears while your app
  /// isn't in use") that was never tested on a device, and flagged that ~20-minute check as where to
  /// start. This is that check.
  ///
  /// The Lock Screen is not reachable from XCUITest — a UI test cannot lock the device. But the
  /// Dynamic Island is just Springboard chrome, so it is in every `XCUIScreen.main.screenshot()`.
  /// That makes the foreground-vs-background question directly photographable: if the HIG claim
  /// holds, the island is empty while Bundles is in front and populated the moment it isn't.
  ///
  /// Read the attachments in order. `foreground-*` answers "can you see it while using the app",
  /// `background-*` answers "can you see it otherwise", and `after-update-*` answers the question
  /// that actually decides whether a 15s rotation is possible: does an update land while the app is
  /// NOT in the foreground.
  func testLiveActivityVisibility() throws {
    let bundles = XCUIApplication(bundleIdentifier: "com.nikhilsinha.bundles")
    let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")

    bundles.terminate()
    Thread.sleep(forTimeInterval: 2)
    bundles.launch()
    Thread.sleep(forTimeInterval: 8)   // session restore + the paired-guard settling

    // The dev control is at the bottom of the home tab, below the widget preview.
    bundles.swipeUp()
    Thread.sleep(forTimeInterval: 1)

    let start = bundles.descendants(matching: .any)["activity-dev-start"]
    guard start.waitForExistence(timeout: 20) else {
      attach(XCUIScreen.main.screenshot(), named: "FAILED-no-dev-control")
      XCTFail("dev control not found — is SHOW_ACTIVITY_DEV_CONTROL true in this build?")
      return
    }
    start.tap()
    Thread.sleep(forTimeInterval: 4)

    // The status line prints ActivityKit's verbatim error if start threw. Screenshot it either way:
    // "nothing on the island" and "start threw LiveActivitiesNotSupported" look identical from the
    // home screen, and only this picture tells them apart.
    attach(XCUIScreen.main.screenshot(), named: "foreground-after-start")

    // Q1: is it visible while the app IS in use? (HIG says no.)
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 4)
    attach(XCUIScreen.main.screenshot(), named: "background-island")

    // Expanded presentation — a long press on the island. Coordinates, because the island has no
    // addressable accessibility element of its own.
    let island = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.022))
    island.press(forDuration: 1.2)
    Thread.sleep(forTimeInterval: 2)
    attach(XCUIScreen.main.screenshot(), named: "background-island-expanded")
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 2)

    // Q2 — the one that decides rotation: does an update land when the app is not in front?
    // Re-enter, tap Update, leave immediately, and photograph the island.
    bundles.activate()
    Thread.sleep(forTimeInterval: 3)
    let update = bundles.descendants(matching: .any)["activity-dev-update"]
    if update.waitForExistence(timeout: 10) {
      update.tap()
      Thread.sleep(forTimeInterval: 2)
      XCUIDevice.shared.press(.home)
      Thread.sleep(forTimeInterval: 4)
      attach(XCUIScreen.main.screenshot(), named: "after-update-island")
    }

    // Notification Center carries Live Activities too, and is the closest scriptable stand-in for
    // the Lock Screen.
    let top = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.0))
    let down = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.7))
    top.press(forDuration: 0.1, thenDragTo: down)
    Thread.sleep(forTimeInterval: 3)
    attach(XCUIScreen.main.screenshot(), named: "notification-center-activity")
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 2)

    // Clean up, and prove end() works — a stuck activity is its own bug.
    bundles.activate()
    Thread.sleep(forTimeInterval: 3)
    let end = bundles.descendants(matching: .any)["activity-dev-end"]
    if end.waitForExistence(timeout: 10) {
      end.tap()
      Thread.sleep(forTimeInterval: 3)
      XCUIDevice.shared.press(.home)
      Thread.sleep(forTimeInterval: 4)
      attach(XCUIScreen.main.screenshot(), named: "after-end-island")
    }
  }

  /// Prove the Live Activity actually renders the partner's picture — status string *and* pixels.
  ///
  /// This exists because `testLiveActivityVisibility` passed for a week while the image was a flat
  /// grey box: every assertion it made was about text, so nothing could fail. Two checks close that,
  /// and they fail for different reasons, which is the point:
  ///
  /// 1. **The status line**, read out of the accessibility tree rather than squinted at in a
  ///    screenshot (it sits below the tab bar and gets cropped). `— photo +image …` means an
  ///    absolute `file://` URI reached the layout; `(no image)` means the app-side resolution
  ///    failed and the layout is innocent. That one string splits the whole diagnosis in two.
  /// 2. **The pixels** in the expanded Dynamic Island's leading slot. ActivityKit draws a flat grey
  ///    box for an image asset bigger than the presentation showing it — a successful `start` with
  ///    no picture and no error anywhere. Grey is achromatic, a photo is not, so requiring some
  ///    colour in that slot is a check the grey-box bug fails and a real render passes. Measured on
  ///    the broken build, that region scored max-chroma 0.
  func testLiveActivityImageRenders() throws {
    let bundles = XCUIApplication(bundleIdentifier: "com.nikhilsinha.bundles")
    let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")

    bundles.terminate()
    Thread.sleep(forTimeInterval: 2)
    bundles.launch()
    Thread.sleep(forTimeInterval: 10)

    bundles.swipeUp()
    Thread.sleep(forTimeInterval: 1)
    bundles.swipeUp()
    Thread.sleep(forTimeInterval: 1)

    let start = bundles.descendants(matching: .any)["activity-dev-start"]
    guard start.waitForExistence(timeout: 20) else {
      attach(XCUIScreen.main.screenshot(), named: "FAILED-no-dev-control")
      XCTFail("dev control not found — is SHOW_ACTIVITY_DEV_CONTROL true in this build?")
      return
    }

    // Clear anything a previous run left running. ActivityKit caps concurrent activities per app,
    // and once that cap is hit `start` throws `ERR_START_LIVE_ACTIVITY` — which reads exactly like
    // "the feature is broken" and is really just an un-cleaned-up device.
    let end = bundles.descendants(matching: .any)["activity-dev-end"]
    if end.waitForExistence(timeout: 10) {
      for _ in 0..<6 {
        end.tap()
        Thread.sleep(forTimeInterval: 1.5)
      }
    }

    start.tap()
    Thread.sleep(forTimeInterval: 8)

    let statusElement = bundles.descendants(matching: .any)["activity-dev-status"]
    XCTAssertTrue(statusElement.waitForExistence(timeout: 10), "dev status line not found")
    let status = statusElement.label
    let attachment = XCTAttachment(string: status)
    attachment.name = "activity-dev-status"
    attachment.lifetime = .keepAlways
    add(attachment)
    print("ACTIVITY_DEV_STATUS >>> \(status)")
    attach(XCUIScreen.main.screenshot(), named: "status-in-app")

    XCTAssertTrue(status.hasPrefix("start OK"), "start did not succeed: \(status)")
    XCTAssertTrue(
      status.contains("+image"),
      "the activity started with no image at all — the failure is app-side (resolveActivityImage / "
        + "widgetsDirectory / the download), not in the layout: \(status)"
    )

    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 4)
    attach(XCUIScreen.main.screenshot(), named: "island-compact")

    // Expanded presentation — a long press on the island. Coordinates, because the island has no
    // addressable accessibility element of its own.
    let island = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.022))
    island.press(forDuration: 1.2)
    Thread.sleep(forTimeInterval: 3)
    let expanded = XCUIScreen.main.screenshot()
    attach(expanded, named: "island-expanded")
    assertIsAPicture(expanded, region: Self.expandedLeadingSlot, named: "island-expanded-leading")
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 2)

    // The lock screen is not reachable from XCUITest — a UI test cannot lock the device. Notification
    // Center renders the *same* `banner` presentation, so it is the closest scriptable stand-in, and
    // the one CLAUDE.md already uses for push verification.
    let top = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.0))
    let down = springboard.coordinate(withNormalizedOffset: CGVector(dx: 0.1, dy: 0.7))
    top.press(forDuration: 0.1, thenDragTo: down)
    Thread.sleep(forTimeInterval: 3)
    attach(XCUIScreen.main.screenshot(), named: "notification-center-activity")
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 2)
  }

  /// The expanded Dynamic Island's leading slot, in fractions of the screen.
  ///
  /// Normalised so it survives a different device; measured against the 1206x2622 iPhone 17 capture,
  /// where the 44pt thumbnail lands entirely inside it with a margin of island-black on every side.
  private static let expandedLeadingSlot = CGRect(x: 0.08, y: 0.038, width: 0.12, height: 0.047)

  /// Fail unless `region` of `screenshot` contains actual colour, and attach the crop either way.
  ///
  /// Chroma — `max(r,g,b) - min(r,g,b)` — is the discriminator because every way this has failed is
  /// achromatic: ActivityKit's grey placeholder, the island's black ground, an empty slot. A
  /// photograph of a person is not. On the broken build this region scored max 0 / mean 0.0.
  private func assertIsAPicture(_ screenshot: XCUIScreenshot, region: CGRect, named name: String) {
    guard let cgImage = screenshot.image.cgImage else {
      XCTFail("\(name): screenshot had no CGImage")
      return
    }
    let width = max(1, Int(region.width * CGFloat(cgImage.width)))
    let height = max(1, Int(region.height * CGFloat(cgImage.height)))
    let cropRect = CGRect(
      x: Int(region.minX * CGFloat(cgImage.width)),
      y: Int(region.minY * CGFloat(cgImage.height)),
      width: width,
      height: height
    )
    guard let cropped = cgImage.cropping(to: cropRect) else {
      XCTFail("\(name): could not crop \(cropRect) out of \(cgImage.width)x\(cgImage.height)")
      return
    }

    let crop = XCTAttachment(image: UIImage(cgImage: cropped))
    crop.name = name
    crop.lifetime = .keepAlways
    add(crop)

    var pixels = [UInt8](repeating: 0, count: width * height * 4)
    guard let context = CGContext(
      data: &pixels,
      width: width,
      height: height,
      bitsPerComponent: 8,
      bytesPerRow: width * 4,
      space: CGColorSpaceCreateDeviceRGB(),
      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
    ) else {
      XCTFail("\(name): could not build a bitmap context")
      return
    }
    context.draw(cropped, in: CGRect(x: 0, y: 0, width: width, height: height))

    var total = 0
    var peak = 0
    for index in stride(from: 0, to: width * height * 4, by: 4) {
      let r = Int(pixels[index]), g = Int(pixels[index + 1]), b = Int(pixels[index + 2])
      let chroma = max(r, max(g, b)) - min(r, min(g, b))
      total += chroma
      peak = max(peak, chroma)
    }
    let mean = Double(total) / Double(width * height)
    print("PIXELS \(name) >>> maxChroma=\(peak) meanChroma=\(String(format: "%.2f", mean))")

    XCTAssertGreaterThan(
      peak, 25,
      "\(name) is achromatic (maxChroma \(peak), mean \(mean)) — ActivityKit is drawing its grey "
        + "placeholder instead of the image. The usual cause is an image asset larger than the "
        + "presentation drawing it; see ACTIVITY_RENDER_MAX_DIMENSION."
    )
    XCTAssertGreaterThan(mean, 4.0, "\(name) has almost no colour anywhere (mean chroma \(mean))")
  }

  /// Capture every home-screen page.
  ///
  /// Locating the Bundles widget programmatically is unreliable — a widget's accessibility tree is
  /// opaque and its label depends on whatever content it happens to be rendering. And picking a
  /// single page is worse: `springboard.activate()` returns to the last-shown page (which is luck),
  /// while pressing home jumps to page one (where the widget may not live). Either way you can
  /// silently photograph the wrong page and conclude the widget vanished.
  ///
  /// So don't choose. Walk every page and attach them all; whoever reads the results can see the
  /// widget wherever it actually is.
  private func captureAllHomePages(prefix: String, maxPages: Int = 5) {
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 1.5)
    XCUIDevice.shared.press(.home)   // from the home screen, this jumps to page one
    // WidgetKit draws asynchronously after Springboard appears; capturing immediately can catch a
    // placeholder or a half-drawn widget and look like a rendering bug that isn't one.
    Thread.sleep(forTimeInterval: 4)

    let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
    for page in 1...maxPages {
      attach(XCUIScreen.main.screenshot(), named: "\(prefix)-page\(page)")
      springboard.swipeLeft()
      Thread.sleep(forTimeInterval: 1.5)
    }
  }

  private func attach(_ screenshot: XCUIScreenshot, named name: String) {
    let attachment = XCTAttachment(screenshot: screenshot)
    attachment.name = name
    // Without .keepAlways the attachment is discarded on success — and success is exactly the case
    // we want the picture for.
    attachment.lifetime = .keepAlways
    add(attachment)
  }
}
