import XCTest

/// Photographs the iPhone's home screen so the Bundles widget can be verified without a human
/// looking at the phone.
///
/// Why this exists: `devicectl` has no screenshot command, and libimobiledevice's
/// `idevicescreenshot` needs the legacy developer disk image, which Xcode stops shipping after
/// iOS 16.4 — on iOS 17+ the `screenshotr` service is simply refused. XCUITest is the one path
/// that still works, because the test runs *on* the device and `XCUIScreen.main.screenshot()`
/// captures whatever is on screen, Springboard included.
///
/// This target deliberately lives outside `ios/` — that directory is regenerated by
/// `npx expo prebuild`, which would delete anything added to the app project.
final class WidgetShotUITests: XCTestCase {

  override func setUpWithError() throws {
    continueAfterFailure = false
  }

  /// Go to the home screen and attach a full-screen capture to the test results.
  func testCaptureHomeScreen() throws {
    captureAllHomePages(prefix: "home")
  }

  /// Open Bundles (which triggers `useWidgetSync` -> `advanceStack` -> `updateSnapshot`), return to the
  /// home screen, and capture. This is the "does one app open change the widget" test — run it
  /// repeatedly to watch the smart stack advance.
  func testOpenBundlesThenCaptureHomeScreen() throws {
    let bundles = XCUIApplication(bundleIdentifier: "com.nikhilsinha.bundles")
    bundles.launch()

    // The sync does a network fetch, a signed-URL round trip, and an image download before it calls
    // updateSnapshot. Cutting this short kills the sync mid-flight.
    Thread.sleep(forTimeInterval: 10)
    attach(XCUIScreen.main.screenshot(), named: "in-app")

    captureAllHomePages(prefix: "after-open")
  }

  /// Capture every home-screen page.
  ///
  /// Locating the Bundles widget programmatically is unreliable — a widget's accessibility tree is
  /// opaque and its label depends on whatever content it happens to be rendering. And picking a
  /// single page is worse: `springboard.activate()` returns to the last-shown page (which is luck),
  /// while pressing home jumps to page one (where the widget may not live). Either way you can
  /// silently photograph the wrong page and conclude the widget vanished.
  ///
  /// So don't choose. Walk every page and attach them all; whoever reads the results can see the
  /// widget wherever it actually is.
  private func captureAllHomePages(prefix: String, maxPages: Int = 5) {
    XCUIDevice.shared.press(.home)
    Thread.sleep(forTimeInterval: 1.5)
    XCUIDevice.shared.press(.home)   // from the home screen, this jumps to page one
    // WidgetKit draws asynchronously after Springboard appears; capturing immediately can catch a
    // placeholder or a half-drawn widget and look like a rendering bug that isn't one.
    Thread.sleep(forTimeInterval: 4)

    let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
    for page in 1...maxPages {
      attach(XCUIScreen.main.screenshot(), named: "\(prefix)-page\(page)")
      springboard.swipeLeft()
      Thread.sleep(forTimeInterval: 1.5)
    }
  }

  private func attach(_ screenshot: XCUIScreenshot, named name: String) {
    let attachment = XCTAttachment(screenshot: screenshot)
    attachment.name = name
    // Without .keepAlways the attachment is discarded on success — and success is exactly the case
    // we want the picture for.
    attachment.lifetime = .keepAlways
    add(attachment)
  }
}
